export const Players = [
  {
    first: 'Kyle',
    last: 'Lanham',
    position: 'GK',
    number: 1,
    reserve: false,
    pic: null,
  },
  {
    first: 'Grant',
    last: 'Reuter',
    position: 'DEF',
    number: 2,
    reserve: false,
    pic: null,
  },
  {
    first: 'Oscar',
    last: 'Scruggins',
    position: 'DEF',
    number: 3,
    reserve: false,
    pic: null,
  },
  {
    first: 'Guido ',
    last: 'Carvaro ',
    position: 'MID',
    number: 4,
    reserve: false,
    pic: null,
  },
  {
    first: 'Tony',
    last: 'Sabo',
    position: 'DEF',
    number: 5,
    reserve: false,
    pic: null,
  },
  {
    first: 'Dale ',
    last: 'Oppresser ',
    position: 'DEF',
    number: 6,
    reserve: false,
    pic: null,
  },
  {
    first: 'Hector',
    last: 'Salgado',
    position: 'MID',
    number: 7,
    reserve: false,
    pic: null,
  },
  {
    first: 'Ethan',
    last: 'Nosky',
    position: 'DEF',
    number: 8,
    reserve: false,
    pic: null,
  },
  {
    first: 'Christian ',
    last: 'Paget',
    position: 'FWD',
    number: 9,
    reserve: false,
    pic: null,
  },
  {
    first: 'Bilal ',
    last: 'Madjour',
    position: 'MID',
    number: 10,
    reserve: false,
    pic: null,
  },
  {
    first: 'Michael ',
    last: 'Podsiadly ',
    position: 'FWD',
    number: 11,
    reserve: false,
    pic: null,
  },
  {
    first: 'Patrick',
    last: 'Garland',
    position: 'DEF',
    number: 12,
    reserve: false,
    pic: null,
  },
  {
    first: 'Eli',
    last: 'Steinberg',
    position: 'DEF',
    number: 13,
    reserve: false,
    pic: null,
  },
  {
    first: 'Zach',
    last: 'Paget',
    position: 'MID',
    number: 14,
    reserve: false,
    pic: null,
  },
  {
    first: 'Jacob',
    last: 'Kern',
    position: 'MID',
    number: 15,
    reserve: false,
    pic: null,
  },
  {
    first: 'Matt ',
    last: 'Pergram',
    position: 'MID',
    number: 17,
    reserve: false,
    pic: null,
  },
  {
    first: 'Chris',
    last: 'Higginson',
    position: 'MID',
    number: 18,
    reserve: false,
    pic: null,
  },
  {
    first: 'Alex',
    last: 'Molchan ',
    position: 'FWD',
    number: 19,
    reserve: false,
    pic: null,
  },
  {
    first: 'Assa ',
    last: 'Ramirez',
    position: 'CM',
    number: 20,
    reserve: false,
    pic: null,
  },
  {
    first: 'Greg',
    last: 'Fiorillo',
    position: 'DEF',
    number: 21,
    reserve: false,
    pic: null,
  },
  {
    first: 'Tyler ',
    last: 'Markell',
    position: 'FWD',
    number: 22,
    reserve: false,
    pic: null,
  },
  {
    first: 'Gama',
    last: 'Ramirez',
    position: 'MID',
    number: 24,
    reserve: false,
    pic: null,
  },
  {
    first: 'Kayle',
    last: 'Lowdermilk',
    position: 'DEF',
    number: 25,
    reserve: false,
    pic: null,
  },
  {
    first: 'Malcom',
    last: 'Jeffris',
    position: 'CM',
    number: 26,
    reserve: false,
    pic: null,
  },
  {
    first: 'Frank',
    last: 'Veiga',
    position: 'DEF',
    number: 27,
    reserve: false,
    pic: null,
  },
  {
    first: 'Dehrian',
    last: 'Ramierez',
    position: 'DEF',
    number: 28,
    reserve: false,
    pic: null,
  },
  {
    first: 'Juan',
    last: 'Grijalva',
    position: 'MID',
    number: 29,
    reserve: false,
    pic: null,
  },
  {
    first: 'Preston',
    last: 'Harless ',
    position: 'GK',
    number: 35,
    reserve: false,
    pic: null,
  },
];
